# Generated by Django 2.2.4 on 2019-08-07 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=50)),
                ('incidencia', models.ManyToManyField(to='checador.Incidencia')),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checador.Registro')),
            ],
        ),
        migrations.AddField(
            model_name='incidencia',
            name='registros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checador.Registro'),
        ),
    ]
