# Generated by Django 2.2.4 on 2019-08-07 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='nombre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_incidencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nombre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_registro', to=settings.AUTH_USER_MODEL),
        ),
    ]
