# Generated by Django 2.2.4 on 2019-08-07 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checador', '0002_incidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checador.Incidencia')),
            ],
        ),
    ]
