# Generated by Django 2.2.4 on 2019-08-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checador', '0002_auto_20190807_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mese',
            new_name='Meses',
        ),
    ]
