# Generated by Django 2.2.4 on 2019-08-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checador', '0003_auto_20190812_1422'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meses',
            new_name='Mese',
        ),
    ]
