# Generated by Django 2.2.4 on 2019-08-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checador', '0004_meses_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meses',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
