# Generated by Django 2.2.4 on 2019-08-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checador', '0005_auto_20190806_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meses',
            name='nombre',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre'), (13, 'Mes')], default=13),
        ),
    ]
