# Generated by Django 2.2.4 on 2019-08-07 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checador', '0007_auto_20190806_2348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meses',
            new_name='Mes',
        ),
    ]
