# Generated by Django 2.2.4 on 2019-08-07 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checador', '0008_auto_20190806_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=50)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checador.Incidencia')),
            ],
        ),
        migrations.DeleteModel(
            name='Mes',
        ),
    ]
