# Generated by Django 2.2.4 on 2019-08-07 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checador', '0009_auto_20190807_0002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meses',
            new_name='Mese',
        ),
    ]
