# Generated by Django 2.2.4 on 2019-08-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('ubicacion', models.ManyToManyField(to='Sucursal.Ubicacion')),
            ],
        ),
    ]
