# Generated by Django 2.2.4 on 2019-08-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursal', '0002_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
