# Generated by Django 2.2.4 on 2019-08-08 05:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sucursal', '0003_areas_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areas',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='areas',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='gerente',
        ),
        migrations.AddField(
            model_name='areas',
            name='empleado',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='area',
            field=models.ManyToManyField(to='Sucursal.Areas'),
        ),
    ]
